### ISSUE TITLE
Infografia Jazmin

### ISSUE THREAD

**Issue by JazminloRI** [SistemasTecTlaxiaco/actividad-1-infografia-de-realidad-aumentada-JazminloRI#1]
![Infografia](https://user-images.githubusercontent.com/79929372/221672655-aa663a45-82f5-4585-b740-d0924f729e60.jpg)

**Comment by josealfredo79** [comment]
Calificacion????

**Comment by IsraelNicolas61** [comment]
Calificación 20/20

**Comment by josealfredo79** [comment]
Bien hecho y revisado
